[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/static/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/documents/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000"
    Content-Disposition = "inline"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["*"]}
